services:
  web:
    build: .

    container_name: gofi_app

    volumes:
      - .:/app
      - chroma_data:/app/chroma_db

    ports:
      - "8000:8000"

    env_file:
      - .env

volumes:
  chroma_data: