# Generated by Django 6.0.7 on 2026-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
    ]
