# Generated by Django 6.0.7 on 2026-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_user_note_summary_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='embedding_status',
            field=models.BooleanField(default=False),
        ),
    ]
